---
name: Deploy
run-name: Deploy triggered by @${{ github.actor }}

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'static/**'
      - 'pnpm-lock.yaml'
      - 'package.json'
      - 'tsconfig.json'
      - 'svelte.config.ts'
      - 'svelte-sitemap.config.ts'
      - 'vite.config.ts'
      - 'vitest.config.ts'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Allow only one concurrent deployment,
# skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want
# to allow these production deployments to complete.
concurrency:
  group: 'deploy'
  cancel-in-progress: false

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2
        with:
          fetch-depth: 0
      - name: Set up Vite+
        uses: voidzero-dev/setup-vp@v1
        with:
          node-version: 24
      - name: Cache Vite-Plus dependencies
        uses: actions/cache@v5.0.4
        with:
          path: ~/.vite-plus
          key: web-vite-plus-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            web-vite-plus-${{ hashFiles('**/pnpm-lock.yaml') }}
      - name: Install dependencies
        run: vp install
      - name: Sync SvelteKit
        run: vp run sv-sync
      - name: Create Website
        run: vp build
      - name: Setup Pages
        uses: actions/configure-pages@v6.0.0
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4.0.0
        with:
          path: 'build'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
